name: slack-notification
on:
  release:
    types: [published]

jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a package is released
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ github.event.release.tag_name }}"
          echo "${{ github.event.release.name }}"
          echo "${{ github.event.release.body }}"
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C01PVCCH0DC
          slack-text: New Paste release "${{ github.event.release.name }}", "${{ github.event.release.tag_name }}"
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
